[package]
name = "normal_form"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serde = 
# serde_json = "1.0"
num = "0.4.0"
anyhow = "1.0.65"
nalgebra = "0.31.2"
# thiserror = "1.0"
